@echo off
echo Starting backend...
start "Backend Server" cmd /k "cd backend && node server.js"

echo Waiting for backend to start...
timeout /t 5 /nobreak

echo Starting Flutter app...
cd life_solver
echo running flutter clean...
call flutter clean
echo running flutter pub get...
call flutter pub get
echo running flutter run...
flutter run -d windows
